---
title: "Unit2_The Statistical Sommelier: An Introduction to Linear Regression"
output: pdf_document
---

```{r}
wine <- read.csv('wine.csv')
```

One-variable linear regression

```{r}
model1 = lm(Price ~ AGST, data = wine)
summary(model1)
```

Multiple R-squared will always increase if you add more variable.
Adjusted R-squared will decrease if you add variable that doesn't necessarily help the model.

```{r}
SSE = sum(model1$residuals^2)
SSE
```

```{r}
model2 = lm(Price ~ AGST + HarvestRain, data = wine)
summary(model2)
```

Since the multiple R-squared and the adjusted R-squared both increase significantly, we can say that this new variable HarvestRain really help our model.

```{r}
SSE = sum(model2$residuals^2)
SSE
```

```{r}
model3 = lm(Price ~ AGST + HarvestRain + WinterRain + Age + FrancePop, data = wine)
summary(model3)
```

```{r}
SSE = sum(model3$residuals^2)
SSE
```

```{r}
model4 = lm(Price ~ AGST + HarvestRain + WinterRain + Age, data = wine)
summary(model4)
```

```{r}
cor(wine$WinterRain, wine$Price)

cor(wine$Age, wine$FrancePop)

cor(wine)
```

```{r}
model5 = lm(Price ~ WinterRain + AGST + HarvestRain, data = wine)
summary(model5)
```

```{r}
wine_test = read.csv("wine_test.csv")
str(wine_test)
```

```{r}
predictTest = predict(model4, newdata = wine_test)
predictTest
```

```{r}
SSE = sum((wine_test$Price - predictTest)^2)
SST = sum((wine_test$Price - mean(wine$Price))^2)
SSE
SST
1 - SSE/SST
```

