---
title: "Unit3_Election Forecasting"
output: html_notebook
---

```{r}
polling = read.csv("PollingData.csv")
str(polling)
summary(polling)
```

```{r}
# Let's deal with the missing values
# install.packages("mice")
library(mice)
simple = polling[c("Rasmussen","SurveyUSA","DiffCount","PropR")]
summary(simple)
```

```{r}
set.seed(144)
imputed = complete(mice(simple))
# Copy back to the initial dataframe
polling$Rasmussen = imputed$Rasmussen
polling$SurveyUSA = imputed$SurveyUSA
# Check
summary(polling) # No more missing values.

```

```{r}
train = subset(polling,Year == 2004 | Year == 2008)
test = subset(polling, Year == 2012)

# Baseline model
table(train$Republican)
# The baseline model would be to predict 1 (Republican wins the states). Accuracy = 53%
```

```{r}
# Smarter baseline model using Rasmussen
table(train$Republican, sign(train$Rasmussen))

# This baseline method is better because it successfully classifies 94 of the cases right. Only 4 states are wrong and 2 are inconclusive.
```

```{r}
# Check for multicollinearity
cor(train[c("Rasmussen","SurveyUSA","DiffCount","PropR","Republican")])
# Most of the data are correlated!!!
```

```{r}
# Build a model with only single dependent variable
mod1 = glm(Republican ~ PropR, data = train, family = binomial)
summary(mod1)
```

```{r}
pred1 = predict(mod1, type="response")
table(train$Republican, pred1 > 0.5) # Make four mistakes. Can we include by adding new variables?
```

```{r}
mod2 = glm(Republican ~ SurveyUSA + DiffCount, data = train, family = binomial)
pred2 = predict(mod2, type="response")
table(train$Republican, pred2 > 0.5) # Make only three mistakes now!
```

```{r}
summary(mod2)
# The AIC is a little bit smaller, which means stronger model.
```

```{r}
table(test$Republican, sign(test$Rasmussen)) # The smart baseline method produces 4 wrong and 2 inconclusive
predTest = predict(mod2, newdata = test, type = "response")
table(test$Republican, predTest > 0.5) # This model produces only 1 wrong.
```

```{r}
# Pull out to see why the prediction is wrong.
subset(test, predTest >= 0.5 & Republican == 0)
```





